### ISSUE TITLE
Cachet connector calls CachetHQ's API even if nothing changed

### ISSUE THREAD

**Issue by gfriloux** [Lex-Persona/SupExt#10]
Every check run will trigger a call to CachetHQ's API to update component's status.
On its side, CachetHQ will send mails to any suscribed users, when a component is updated.

Mails will look like this : 
> Mattermost status changed from Opérationnel to Opérationnel.

So it seems to me that SupExt should not call CachetHQ without a reason to.
The fact that i do have almost 30 checks, means SupExt is going to make 30 HTTP queries to the CachetHQ server, while nothing new happenned.

I might soon get up to 100 checks, so it would be better to not do any update query if nothing changed.
One thing to keep in mind too : One CachetHQ component can have multiple checks linked to it.
Saying this to avoid having one check failing, putting Component to fail state, and being resolved by the next check, which is successfull.

**Comment by gfriloux** [comment]
Additional information : I am using branch 2.4 of CachetHQ

**Comment by gfriloux** [comment]
Looking at the Cachet connector.
Im seeing that getId is also called at each test.

I believe we should add a list of components inside the cachet connector that will keep : 
1. Current component state
2. Component's ID

This way, we might be able to load components at start, fetch all the IDs, and never fetch them again.
Another solution is to ask for components IDs in the configuration file, just like cachet-monitor does.

Saving the state would allow to not send any http query at each check.
Then, we would a proper way to keep a component in failed state if at least one check fails.

**Comment by prototux** [comment]
It shouldn't call cachet if cachet's current status is already good/bad for a given component, that's a bug as it will trigger alerts for nothing as you've pointed out.

Though, it shouldn't store the state and the components, because we can't assume that nothing has changed cachet's status between test (be it an human operator or another script that does API calls). this, we should call cachet's API to get the current status, and update it only if needed. that will still do calls to API (and these API calls, as well as the connector name/id one, shouldn't be expensive, so it's not a high priority issue). these are probably separate issues.

Loading of cachet IDs at init instead of each call is a good idea, but requires lots of changes on the code. same for the multiple checks for one ID case. these two are also probably better in a separate issue.

**Comment by gfriloux** [comment]
Another problem is that an admin might change the status of a component for reasons not monitored by SupExt.

In this case, SupExt will override this change by putting component at "Ok" state just because its sensors are OK
